#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Library/Python/3.7/site-packages/neuron/.data"
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/joao/Research/Models/NetPyNE/M1/mod/x86_64/.libs/libnrnmech.so" "$@"
